### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Vyzeon** [SCCapstone/Accountability-Pods#157]
With the addition of the organization accounts, the difference in posts and other things of that nature, is that enough for me to make a good grade in this class? I am still trying to figure out a few things with the timed portion of the posts so that's why I haven't committed anything yet, but I hope to finish it in the next couple of days.
Also, I realized that I do not have access to the Test Flight account since that Apple ID was one of the group members personal apple accounts, what do you want me to do about that?

**Comment by josemvidal** [comment]
We agreed on #155 and #156 with [my comments](https://github.com/SCCapstone/Accountability-Pods/issues/156#issuecomment-847143605). So, that is what you should do.

Remember that developers commit every day, maybe several times. Each time a new little thing works, commit. It is how we get things done, and see what others did.

You will have to get your own tesflight account. That is the Apple way.
