### ISSUE TITLE
Milestone Video

### ISSUE THREAD

**Issue by Vyzeon** [SCCapstone/Accountability-Pods#158]
Is there a certain time that the video needs to be turned in at? Or is it just any time as long as its sometime tomorrow?

**Comment by josemvidal** [comment]
Anytime in the day is OK.

**Comment by Vyzeon** [comment]
https://user-images.githubusercontent.com/70242022/127723338-4c7f0137-7114-4652-9f23-43317db01ccd.mov

Your email should have an email from TestFlight allowing you to download the app. Also just a heads up, UI tests have been acting weird the whole time I worked on them, sometimes they work, sometimes they don't, no idea why that is. I've tried multiple version of Xcode just in case but to no avail.
